import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Link } from "react-router-dom";
import { Brain, ArrowLeft, Calendar, TrendingUp, User, Award } from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from "recharts";

const AttendanceDetails = () => {
  // Function to handle attendance report download
  const handleDownloadReport = () => {
    // In a real app, this would generate and download a PDF report
    // For now, we'll simulate the download with an alert
    alert("Downloading attendance report... In a real application, this would generate a PDF with detailed attendance information.");
    
    // Simulate file download
    const reportContent = `
ECHO-FIVE - Attendance Report
=============================

Student: Emma Johnson
Grade: 8
School: Spring Valley School
Date: ${new Date().toLocaleDateString()}

Overall Attendance Rate: 98%
Days Present: 62/63
Perfect Months: 3/4

Monthly Attendance:
${attendanceHistory.map(month => `- ${month.month}: ${month.attendance}%`).join('\n')}

Recent Attendance Records:
${recentAttendance.map(day => `- ${day.date} (${day.day}): ${day.status}`).join('\n')}

Absences:
${absences.map(absence => `- ${absence.date}: ${absence.reason} - ${absence.note}`).join('\n')}

Generated by ECHO-FIVE - AI-powered student insights
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Emma_Johnson_Attendance_Report_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Function to handle setting attendance goal
  const handleSetGoal = () => {
    // In a real app, this would open a modal or form to set a goal
    // For now, we'll show an alert with information
    const goal = prompt("Set your attendance goal for the next month (e.g., 95%, 98%, 100%):", "100%");
    
    if (goal) {
      alert(`Attendance goal set to ${goal} for the next month! You'll receive reminders to help achieve this goal.`);
    }
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="bg-white border-b border-border sticky top-0 z-50">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <Link to="/dashboard">
              <Button variant="ghost" size="icon">
                <ArrowLeft className="h-5 w-5" />
              </Button>
            </Link>
            <div className="flex items-center gap-2">
              <Brain className="h-8 w-8 text-accent" />
              <span className="text-2xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                ECHO-FIVE
              </span>
            </div>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-6 py-8">
        {/* Header */}
        <div className="mb-8 animate-fade-in">
          <h1 className="text-4xl font-bold mb-2">Attendance Details</h1>
          <p className="text-muted-foreground text-lg">Emma's attendance record and patterns</p>
        </div>

        {/* Overall Attendance Card */}
        <Card className="mb-8 animate-fade-in">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="h-5 w-5 text-accent" />
              Overall Attendance Summary
            </CardTitle>
            <CardDescription>Current attendance standing and trends</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col md:flex-row gap-8">
              <div className="flex-1">
                <div className="flex items-end gap-4 mb-6">
                  <div className="text-6xl font-bold">98%</div>
                  <div className="flex items-center gap-2 text-green-500">
                    <TrendingUp className="h-5 w-5" />
                    <span className="font-medium">Perfect this month</span>
                  </div>
                </div>
                <p className="text-muted-foreground mb-6">
                  Emma has maintained excellent attendance with only 2 absent days this semester. 
                  Her consistent presence in class contributes significantly to her academic success.
                </p>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-4 rounded-lg bg-secondary/50">
                    <p className="text-sm text-muted-foreground">Days Present</p>
                    <p className="font-semibold">62/63</p>
                  </div>
                  <div className="p-4 rounded-lg bg-secondary/50">
                    <p className="text-sm text-muted-foreground">Perfect Months</p>
                    <p className="font-semibold">3/4</p>
                  </div>
                </div>
              </div>
              
              <div className="flex-1">
                <h3 className="font-semibold mb-4">Monthly Attendance</h3>
                <ResponsiveContainer width="100%" height={200}>
                  <BarChart data={attendanceHistory}>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                    <XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" />
                    <YAxis stroke="hsl(var(--muted-foreground))" domain={[90, 100]} />
                    <Tooltip 
                      contentStyle={{ 
                        backgroundColor: "hsl(var(--background))", 
                        borderColor: "hsl(var(--border))",
                        borderRadius: "var(--radius)",
                      }}
                      formatter={(value) => [`${value}%`, "Attendance"]}
                    />
                    <Bar dataKey="attendance" name="Attendance Rate">
                      {attendanceHistory.map((entry, index) => (
                        <Cell 
                          key={`cell-${index}`} 
                          fill={entry.attendance >= 95 ? "hsl(var(--accent))" : "hsl(var(--destructive))"} 
                        />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Detailed Attendance Records */}
        <div className="grid lg:grid-cols-2 gap-6 mb-8">
          <Card className="animate-fade-in">
            <CardHeader>
              <CardTitle>Recent Attendance Records</CardTitle>
              <CardDescription>Day-by-day attendance for the current month</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {recentAttendance.map((day, index) => (
                  <div key={index} className="flex items-center justify-between p-3 rounded-lg bg-secondary/50">
                    <div className="flex items-center gap-3">
                      <div className={`h-3 w-3 rounded-full ${day.status === 'present' ? 'bg-green-500' : day.status === 'late' ? 'bg-yellow-500' : 'bg-red-500'}`}></div>
                      <div>
                        <p className="font-medium">{day.date}</p>
                        <p className="text-sm text-muted-foreground">{day.day}</p>
                      </div>
                    </div>
                    <span className="capitalize">{day.status}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card className="animate-fade-in">
            <CardHeader>
              <CardTitle>Attendance Insights</CardTitle>
              <CardDescription>Patterns and recommendations</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {insights.map((item, index) => (
                <div key={index} className="p-4 rounded-lg border border-border bg-secondary/50">
                  <div className="flex items-start gap-3">
                    <div className="mt-1 h-6 w-6 rounded-full bg-accent flex items-center justify-center">
                      <span className="text-white text-xs font-bold">{index + 1}</span>
                    </div>
                    <div>
                      <p className="font-medium">{item.title}</p>
                      <p className="text-sm text-muted-foreground mt-1">{item.description}</p>
                    </div>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Absence Details */}
        <Card className="mb-8 animate-fade-in">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <User className="h-5 w-5 text-accent" />
              Absence Details
            </CardTitle>
            <CardDescription>Information about Emma's absent days</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {absences.map((absence, index) => (
                <div key={index} className="flex items-start gap-4 p-4 rounded-lg border border-border">
                  <div className="h-10 w-10 rounded-full bg-red-500/20 flex items-center justify-center">
                    <Calendar className="h-5 w-5 text-red-500" />
                  </div>
                  <div>
                    <p className="font-medium">{absence.date}</p>
                    <p className="text-sm text-muted-foreground">{absence.reason}</p>
                    <p className="text-sm mt-1">{absence.note}</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-4 justify-center">
          <Button variant="hero" className="gap-2" onClick={handleDownloadReport}>
            <Calendar className="h-5 w-5" />
            Download Attendance Report
          </Button>
          <Button variant="outline" className="gap-2" onClick={handleSetGoal}>
            <Award className="h-5 w-5" />
            Set Attendance Goal
          </Button>
        </div>
      </div>
    </div>
  );
};

const attendanceHistory = [
  { month: "Aug", attendance: 95 },
  { month: "Sep", attendance: 100 },
  { month: "Oct", attendance: 100 },
  { month: "Nov", attendance: 97 },
];

const recentAttendance = [
  { date: "Nov 15", day: "Wednesday", status: "present" },
  { date: "Nov 14", day: "Tuesday", status: "present" },
  { date: "Nov 13", day: "Monday", status: "present" },
  { date: "Nov 10", day: "Friday", status: "present" },
  { date: "Nov 9", day: "Thursday", status: "present" },
  { date: "Nov 8", day: "Wednesday", status: "present" },
  { date: "Nov 7", day: "Tuesday", status: "present" },
  { date: "Nov 6", day: "Monday", status: "late" },
  { date: "Nov 3", day: "Friday", status: "present" },
  { date: "Nov 2", day: "Thursday", status: "present" },
];

const insights = [
  {
    title: "Consistent Attendance",
    description: "Emma's attendance is consistently above 95%, which correlates with her academic performance."
  },
  {
    title: "Morning Alertness",
    description: "Most of Emma's classes are in the morning when her attendance is highest."
  },
  {
    title: "Extracurricular Balance",
    description: "Emma effectively balances extracurricular activities with school attendance."
  },
];

const absences = [
  {
    date: "October 12",
    reason: "Doctor's appointment",
    note: "Scheduled appointment for annual checkup. Makeup work completed."
  },
  {
    date: "September 5",
    reason: "Family emergency",
    note: "One day absence due to family situation. All assignments caught up."
  }
];

export default AttendanceDetails;