import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { Brain, ArrowLeft, TrendingUp, BarChart3, Clock, BookOpen, Users, Award, Download } from "lucide-react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
} from "recharts";

const EngagementDetails = () => {
  // Function to handle engagement report download
  const handleDownloadReport = () => {
    // In a real app, this would generate and download a PDF report
    // For now, we'll simulate the download with an alert and text file generation
    alert("Downloading engagement report... In a real application, this would generate a PDF with detailed engagement information.");
    
    // Simulate file download
    const reportContent = `
ECHO-FIVE - Engagement Report
=============================

Student: Emma Johnson
Grade: 8
School: Spring Valley School
Date: ${new Date().toLocaleDateString()}

OVERALL ENGAGEMENT
==================
Current Score: 88/100
Last Month: 76/100
Improvement: +12%

ENGAGEMENT HISTORY
==================
${engagementHistory.map(month => `${month.month}: ${month.engagement}/100`).join('\n')}

TIME INVESTMENT
===============
Daily Study Hours:
${studyHours.map(day => `${day.day}: ${day.hours} hours`).join('\n')}

Activity Distribution:
${activityDistribution.map(activity => `${activity.name}: ${activity.value}%`).join('\n')}

PARTICIPATION METRICS
=====================
Class Participation: 92%
Group Work: 88%
Assignment Completion: 95%
Extracurricular: 75%

STRENGTHS
=========
${strengths.map((strength, index) => `${index + 1}. ${strength.title}: ${strength.description}`).join('\n')}

OPPORTUNITIES
=============
${opportunities.map((opportunity, index) => `${index + 1}. ${opportunity.title}: ${opportunity.description}`).join('\n')}

Generated by ECHO-FIVE - AI-powered student insights
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Emma_Johnson_Engagement_Report_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Function to handle setting engagement goal
  const handleSetGoal = () => {
    // In a real app, this would open a modal or form to set a goal
    // For now, we'll show an alert with information
    const goal = prompt("Set your engagement goal for the next month (e.g., 90/100, 95/100):", "90/100");
    
    if (goal) {
      alert(`Engagement goal set to ${goal} for the next month! You'll receive reminders and tips to help achieve this goal.`);
    }
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="bg-white border-b border-border sticky top-0 z-50">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <Link to="/dashboard">
              <Button variant="ghost" size="icon">
                <ArrowLeft className="h-5 w-5" />
              </Button>
            </Link>
            <div className="flex items-center gap-2">
              <Brain className="h-8 w-8 text-accent" />
              <span className="text-2xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                ECHO-FIVE
              </span>
            </div>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-6 py-8">
        {/* Header */}
        <div className="mb-8 animate-fade-in">
          <h1 className="text-4xl font-bold mb-2">Engagement Details</h1>
          <p className="text-muted-foreground text-lg">Emma's participation and involvement in learning activities</p>
        </div>

        {/* Overall Engagement Card */}
        <Card className="mb-8 animate-fade-in">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BarChart3 className="h-5 w-5 text-accent" />
              Overall Engagement Summary
            </CardTitle>
            <CardDescription>Current engagement standing and trends</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col md:flex-row gap-8">
              <div className="flex-1">
                <div className="flex items-end gap-4 mb-6">
                  <div className="text-6xl font-bold">High</div>
                  <div className="flex items-center gap-2 text-green-500">
                    <TrendingUp className="h-5 w-5" />
                    <span className="font-medium">+12% improvement</span>
                  </div>
                </div>
                <p className="text-muted-foreground mb-6">
                  Emma's engagement level has shown significant improvement over the past month. 
                  Her active participation in class discussions and completion of assignments demonstrates 
                  a strong commitment to learning.
                </p>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-4 rounded-lg bg-secondary/50">
                    <p className="text-sm text-muted-foreground">Current Score</p>
                    <p className="font-semibold">88/100</p>
                  </div>
                  <div className="p-4 rounded-lg bg-secondary/50">
                    <p className="text-sm text-muted-foreground">Last Month</p>
                    <p className="font-semibold">76/100</p>
                  </div>
                </div>
              </div>
              
              <div className="flex-1">
                <h3 className="font-semibold mb-4">Engagement Trend</h3>
                <ResponsiveContainer width="100%" height={200}>
                  <LineChart data={engagementHistory}>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                    <XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" />
                    <YAxis stroke="hsl(var(--muted-foreground))" domain={[70, 100]} />
                    <Tooltip 
                      contentStyle={{ 
                        backgroundColor: "hsl(var(--background))", 
                        borderColor: "hsl(var(--border))",
                        borderRadius: "var(--radius)",
                      }}
                      formatter={(value) => [`${value}/100`, "Engagement"]}
                    />
                    <Line 
                      type="monotone" 
                      dataKey="engagement" 
                      stroke="hsl(var(--accent))" 
                      strokeWidth={2}
                      dot={{ stroke: "hsl(var(--accent))", strokeWidth: 2, r: 4 }} 
                      activeDot={{ r: 6 }} 
                    />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Engagement Breakdown */}
        <div className="grid lg:grid-cols-2 gap-6 mb-8">
          <Card className="animate-fade-in">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Clock className="h-5 w-5 text-accent" />
                Time Investment
              </CardTitle>
              <CardDescription>How Emma spends her learning time</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                <div>
                  <h3 className="font-semibold mb-4">Daily Study Hours</h3>
                  <ResponsiveContainer width="100%" height={200}>
                    <BarChart data={studyHours}>
                      <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                      <XAxis dataKey="day" stroke="hsl(var(--muted-foreground))" />
                      <YAxis stroke="hsl(var(--muted-foreground))" />
                      <Tooltip 
                        contentStyle={{ 
                          backgroundColor: "hsl(var(--background))", 
                          borderColor: "hsl(var(--border))",
                          borderRadius: "var(--radius)",
                        }}
                        formatter={(value) => [`${value} hours`, "Study Time"]}
                      />
                      <Bar dataKey="hours" name="Study Hours" fill="hsl(var(--accent))" />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
                
                <div>
                  <h3 className="font-semibold mb-4">Activity Distribution</h3>
                  <ResponsiveContainer width="100%" height={200}>
                    <PieChart>
                      <Pie
                        data={activityDistribution}
                        cx="50%"
                        cy="50%"
                        labelLine={false}
                        outerRadius={80}
                        fill="#8884d8"
                        dataKey="value"
                        label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                      >
                        {activityDistribution.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.color} />
                        ))}
                      </Pie>
                      <Tooltip 
                        formatter={(value) => [`${value}%`, "Time Spent"]}
                        contentStyle={{ 
                          backgroundColor: "hsl(var(--background))", 
                          borderColor: "hsl(var(--border))",
                          borderRadius: "var(--radius)",
                        }}
                      />
                    </PieChart>
                  </ResponsiveContainer>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="animate-fade-in">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Users className="h-5 w-5 text-accent" />
                Participation Metrics
              </CardTitle>
              <CardDescription>Classroom and group activity involvement</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="p-4 rounded-lg bg-secondary/50">
                <div className="flex justify-between items-center mb-2">
                  <p className="font-medium">Class Participation</p>
                  <span className="font-semibold">92%</span>
                </div>
                <p className="text-sm text-muted-foreground">Active contribution during lessons</p>
                <div className="w-full bg-border rounded-full h-2 mt-2">
                  <div className="bg-accent h-2 rounded-full" style={{ width: "92%" }}></div>
                </div>
              </div>
              
              <div className="p-4 rounded-lg bg-secondary/50">
                <div className="flex justify-between items-center mb-2">
                  <p className="font-medium">Group Work</p>
                  <span className="font-semibold">88%</span>
                </div>
                <p className="text-sm text-muted-foreground">Collaboration in team activities</p>
                <div className="w-full bg-border rounded-full h-2 mt-2">
                  <div className="bg-accent h-2 rounded-full" style={{ width: "88%" }}></div>
                </div>
              </div>
              
              <div className="p-4 rounded-lg bg-secondary/50">
                <div className="flex justify-between items-center mb-2">
                  <p className="font-medium">Assignment Completion</p>
                  <span className="font-semibold">95%</span>
                </div>
                <p className="text-sm text-muted-foreground">Timely submission of homework</p>
                <div className="w-full bg-border rounded-full h-2 mt-2">
                  <div className="bg-accent h-2 rounded-full" style={{ width: "95%" }}></div>
                </div>
              </div>
              
              <div className="p-4 rounded-lg bg-secondary/50">
                <div className="flex justify-between items-center mb-2">
                  <p className="font-medium">Extracurricular</p>
                  <span className="font-semibold">75%</span>
                </div>
                <p className="text-sm text-muted-foreground">Participation in learning clubs</p>
                <div className="w-full bg-border rounded-full h-2 mt-2">
                  <div className="bg-accent h-2 rounded-full" style={{ width: "75%" }}></div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Engagement Insights */}
        <Card className="mb-8 animate-fade-in">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BookOpen className="h-5 w-5 text-accent" />
              Engagement Insights
            </CardTitle>
            <CardDescription>Analysis and recommendations</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <h3 className="font-semibold mb-4">Strengths</h3>
                <div className="space-y-4">
                  {strengths.map((strength, index) => (
                    <div key={index} className="p-4 rounded-lg bg-secondary/50">
                      <div className="flex items-start gap-3">
                        <div className="mt-1 h-6 w-6 rounded-full bg-accent flex items-center justify-center">
                          <span className="text-white text-xs font-bold">+</span>
                        </div>
                        <div>
                          <p className="font-medium">{strength.title}</p>
                          <p className="text-sm text-muted-foreground mt-1">{strength.description}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              
              <div>
                <h3 className="font-semibold mb-4">Opportunities</h3>
                <div className="space-y-4">
                  {opportunities.map((opportunity, index) => (
                    <div key={index} className="p-4 rounded-lg border border-border">
                      <div className="flex items-start gap-3">
                        <div className="mt-1 h-6 w-6 rounded-full bg-yellow-500 flex items-center justify-center">
                          <span className="text-white text-xs font-bold">↑</span>
                        </div>
                        <div>
                          <p className="font-medium">{opportunity.title}</p>
                          <p className="text-sm text-muted-foreground mt-1">{opportunity.description}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-4 justify-center">
          <Button variant="hero" className="gap-2" onClick={handleDownloadReport}>
            <Download className="h-5 w-5" />
            Download Engagement Report
          </Button>
          <Button variant="outline" className="gap-2" onClick={handleSetGoal}>
            <Award className="h-5 w-5" />
            Set Engagement Goal
          </Button>
        </div>
      </div>
    </div>
  );
};

const engagementHistory = [
  { month: "Jul", engagement: 72 },
  { month: "Aug", engagement: 76 },
  { month: "Sep", engagement: 80 },
  { month: "Oct", engagement: 84 },
  { month: "Nov", engagement: 88 },
];

const studyHours = [
  { day: "Mon", hours: 2.5 },
  { day: "Tue", hours: 3.0 },
  { day: "Wed", hours: 2.0 },
  { day: "Thu", hours: 3.5 },
  { day: "Fri", hours: 2.0 },
  { day: "Sat", hours: 4.0 },
  { day: "Sun", hours: 3.0 },
];

const activityDistribution = [
  { name: "Homework", value: 40, color: "#8884d8" },
  { name: "Reading", value: 25, color: "#82ca9d" },
  { name: "Projects", value: 20, color: "#ffc658" },
  { name: "Extracurricular", value: 15, color: "#ff8042" },
];

const strengths = [
  {
    title: "Consistent Study Habits",
    description: "Emma maintains regular study schedules and completes assignments on time."
  },
  {
    title: "Active Participation",
    description: "Regularly contributes to class discussions and asks insightful questions."
  },
  {
    title: "Collaborative Spirit",
    description: "Works effectively in group settings and supports peers in learning."
  }
];

const opportunities = [
  {
    title: "Extended Reading",
    description: "Encourage more independent reading to further develop comprehension skills."
  },
  {
    title: "Leadership Roles",
    description: "Provide opportunities for Emma to take leadership roles in group projects."
  },
  {
    title: "Creative Expression",
    description: "Explore creative outlets to enhance engagement through artistic activities."
  }
];

export default EngagementDetails;