import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Link } from "react-router-dom";
import { Brain, ArrowLeft, BookOpen, TrendingUp, Calendar, Award } from "lucide-react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

const GradeDetails = () => {
  // Function to handle report download
  const handleDownloadReport = () => {
    // In a real app, this would generate and download a PDF report
    // For now, we'll simulate the download with an alert
    alert("Downloading full report... In a real application, this would generate a PDF with detailed grade information.");
    
    // Simulate file download
    const reportContent = `
ECHO-FIVE - Academic Performance Report
=======================================

Student: Emma Johnson
Grade: 8
School: Spring Valley School
Date: ${new Date().toLocaleDateString()}

Overall Grade: A- (+0.3 from last week)
GPA: 3.7/4.0
Ranking: Top 15%

Subject Performance:
${subjects.map(subject => `- ${subject.name}: ${subject.grade} (${subject.score}%)`).join('\n')}

Recent Achievements:
${achievements.map(achievement => `- ${achievement.title} (${achievement.date})`).join('\n')}

Recommendations:
${improvements.map((item, index) => `${index + 1}. ${item.title}: ${item.description}`).join('\n')}

Generated by ECHO-FIVE - AI-powered student insights
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Emma_Johnson_Grade_Report_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Function to handle scheduling a meeting
  const handleScheduleMeeting = () => {
    // In a real app, this would open a scheduling interface or send an email
    // For now, we'll show an alert with information
    alert("Scheduling meeting with teacher... In a real application, this would open a calendar interface or send an email to the teacher.");
    
    // Simulate opening an email client
    const subject = encodeURIComponent("Meeting Request: Emma Johnson's Academic Progress");
    const body = encodeURIComponent(`
Dear [Teacher's Name],

I would like to schedule a meeting to discuss Emma Johnson's academic progress. 
Her current overall grade is A- (improved by +0.3 from last week).

I'm particularly interested in discussing:
- Her performance in English class (currently B+)
- Recommendations for improving her writing skills
- Her participation in class activities

Please let me know your availability for a meeting this week.

Best regards,
Sarah Johnson (Parent)
    `);
    
    window.location.href = `mailto:teacher@springvalleyschool.edu?subject=${subject}&body=${body}`;
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="bg-white border-b border-border sticky top-0 z-50">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <Link to="/dashboard">
              <Button variant="ghost" size="icon">
                <ArrowLeft className="h-5 w-5" />
              </Button>
            </Link>
            <div className="flex items-center gap-2">
              <Brain className="h-8 w-8 text-accent" />
              <span className="text-2xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                ECHO-FIVE
              </span>
            </div>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-6 py-8">
        {/* Header */}
        <div className="mb-8 animate-fade-in">
          <h1 className="text-4xl font-bold mb-2">Grade Details</h1>
          <p className="text-muted-foreground text-lg">Comprehensive analysis of Emma's academic performance</p>
        </div>

        {/* Overall Grade Card */}
        <Card className="mb-8 animate-fade-in">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BookOpen className="h-5 w-5 text-accent" />
              Overall Academic Performance
            </CardTitle>
            <CardDescription>Detailed breakdown of current standing</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col md:flex-row gap-8">
              <div className="flex-1">
                <div className="flex items-end gap-4 mb-6">
                  <div className="text-6xl font-bold">A-</div>
                  <div className="flex items-center gap-2 text-green-500">
                    <TrendingUp className="h-5 w-5" />
                    <span className="font-medium">+0.3 from last week</span>
                  </div>
                </div>
                <p className="text-muted-foreground mb-6">
                  Emma's overall performance shows consistent improvement. Her A- average reflects strong 
                  academic abilities across all subjects with particular excellence in Mathematics and Science.
                </p>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-4 rounded-lg bg-secondary/50">
                    <p className="text-sm text-muted-foreground">Ranking</p>
                    <p className="font-semibold">Top 15%</p>
                  </div>
                  <div className="p-4 rounded-lg bg-secondary/50">
                    <p className="text-sm text-muted-foreground">GPA</p>
                    <p className="font-semibold">3.7/4.0</p>
                  </div>
                </div>
              </div>
              
              <div className="flex-1">
                <h3 className="font-semibold mb-4">Performance Trend</h3>
                <ResponsiveContainer width="100%" height={200}>
                  <LineChart data={gradeHistory}>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                    <XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" />
                    <YAxis stroke="hsl(var(--muted-foreground))" />
                    <Tooltip 
                      contentStyle={{ 
                        backgroundColor: "hsl(var(--background))", 
                        borderColor: "hsl(var(--border))",
                        borderRadius: "var(--radius)",
                      }}
                    />
                    <Line 
                      type="monotone" 
                      dataKey="grade" 
                      stroke="hsl(var(--accent))" 
                      strokeWidth={2}
                      dot={{ stroke: "hsl(var(--accent))", strokeWidth: 2, r: 4 }} 
                      activeDot={{ r: 6 }} 
                    />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Subject Breakdown */}
        <div className="grid lg:grid-cols-2 gap-6 mb-8">
          <Card className="animate-fade-in">
            <CardHeader>
              <CardTitle>Subject Performance</CardTitle>
              <CardDescription>Detailed scores across all subjects</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {subjects.map((subject, index) => (
                <div key={index} className="space-y-2">
                  <div className="flex justify-between items-center">
                    <div className="flex items-center gap-3">
                      <div className={`h-10 w-10 rounded-lg ${subject.color} flex items-center justify-center`}>
                        <subject.icon className="h-5 w-5 text-white" />
                      </div>
                      <div>
                        <p className="font-medium">{subject.name}</p>
                        <p className="text-sm text-muted-foreground">Grade: {subject.grade}</p>
                      </div>
                    </div>
                    <span className="font-semibold text-lg">{subject.score}%</span>
                  </div>
                  <Progress value={subject.score} className="h-2" />
                  <p className="text-sm text-muted-foreground">{subject.comment}</p>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="animate-fade-in">
            <CardHeader>
              <CardTitle>Improvement Areas</CardTitle>
              <CardDescription>Recommendations for continued growth</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {improvements.map((item, index) => (
                <div key={index} className="p-4 rounded-lg border border-border bg-secondary/50">
                  <div className="flex items-start gap-3">
                    <div className="mt-1 h-6 w-6 rounded-full bg-accent flex items-center justify-center">
                      <span className="text-white text-xs font-bold">{index + 1}</span>
                    </div>
                    <div>
                      <p className="font-medium">{item.title}</p>
                      <p className="text-sm text-muted-foreground mt-1">{item.description}</p>
                    </div>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-4 justify-center">
          <Button variant="hero" className="gap-2" onClick={handleDownloadReport}>
            <BookOpen className="h-5 w-5" />
            Download Full Report
          </Button>
          <Button variant="outline" className="gap-2" onClick={handleScheduleMeeting}>
            <Calendar className="h-5 w-5" />
            Schedule Meeting with Teacher
          </Button>
        </div>
      </div>
    </div>
  );
};

const gradeHistory = [
  { month: "Jan", grade: 85 },
  { month: "Feb", grade: 86 },
  { month: "Mar", grade: 87 },
  { month: "Apr", grade: 88 },
  { month: "May", grade: 89 },
  { month: "Jun", grade: 90 },
  { month: "Jul", grade: 89 },
  { month: "Aug", grade: 90 },
  { month: "Sep", grade: 91 },
  { month: "Oct", grade: 92 },
];

const subjects = [
  { 
    name: "Mathematics", 
    grade: "A", 
    score: 92, 
    icon: BookOpen, 
    color: "bg-blue-500",
    comment: "Excellent problem-solving skills. Continue with advanced topics."
  },
  { 
    name: "Science", 
    grade: "A-", 
    score: 88, 
    icon: BookOpen, 
    color: "bg-green-500",
    comment: "Strong analytical thinking. Participate more in lab activities."
  },
  { 
    name: "English", 
    grade: "B+", 
    score: 85, 
    icon: BookOpen, 
    color: "bg-purple-500",
    comment: "Good comprehension. Focus on creative writing skills."
  },
  { 
    name: "History", 
    grade: "A", 
    score: 90, 
    icon: BookOpen, 
    color: "bg-orange-500",
    comment: "Exceptional recall and analysis of historical events."
  },
];

const improvements = [
  {
    title: "Enhance Writing Skills",
    description: "Practice creative writing exercises twice a week to improve expression and grammar."
  },
  {
    title: "Participate More in Discussions",
    description: "Join study groups to build confidence in verbal communication."
  },
  {
    title: "Time Management",
    description: "Use planners to balance homework and extracurricular activities effectively."
  },
  {
    title: "Reading Comprehension",
    description: "Read diverse genres to broaden vocabulary and understanding."
  },
];

const achievements = [
  { title: "Top Performer", date: "This week" },
  { title: "Book Worm", date: "2 days ago" },
  { title: "Perfect Attendance", date: "This month" },
];

export default GradeDetails;