import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { Brain, ArrowLeft, TrendingUp, BookOpen, Users, BarChart3, Lightbulb, Download } from "lucide-react";
import {
  Radar,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
} from "recharts";

const Insights = () => {
  // Function to handle downloading the full insights report
  const handleDownloadReport = () => {
    // In a real app, this would generate and download a PDF report
    // For now, we'll simulate the download with an alert and text file generation
    alert("Downloading full insights report... In a real application, this would generate a PDF with detailed insights information.");
    
    // Simulate file download
    const reportContent = `
ECHO-FIVE - Full Insights Report
================================

Student: Emma Johnson
Grade: 8
School: Spring Valley School
Date: ${new Date().toLocaleDateString()}

COGNITIVE SKILLS ANALYSIS
=========================
Logic: 92%
Memory: 85%
Creativity: 88%
Analysis: 95%
Verbal: 82%
Spatial: 90%

STRENGTHS
=========
${strengths.map((strength, index) => `${index + 1}. ${strength.title}: ${strength.description}`).join('\n')}

GROWTH AREAS
============
${growthAreas.map((area, index) => `${index + 1}. ${area.title}: ${area.description}`).join('\n')}

SUBJECT INSIGHTS
================
${subjectInsights.map(subject => `${subject.name}: ${subject.score}% - ${subject.insight}`).join('\n')}

LEARNING TRENDS
===============
${learningTrends.map(trend => `${trend.month}: Engagement ${trend.engagement}%, Performance ${trend.performance}%`).join('\n')}

RECOMMENDATIONS
===============
${recommendations.map((rec, index) => `${index + 1}. ${rec.title}: ${rec.description}`).join('\n')}

Generated by ECHO-FIVE - AI-powered student insights
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Emma_Johnson_Insights_Report_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Function to handle sharing with teacher
  const handleShareWithTeacher = () => {
    // In a real app, this would open a sharing interface or send an email
    // For now, we'll show an alert with information
    alert("Sharing insights with teacher... In a real application, this would open an email interface with the teacher.");
    
    // Simulate opening an email client
    const subject = encodeURIComponent("Emma Johnson's AI Insights Report");
    const body = encodeURIComponent(`
Dear [Teacher's Name],

I wanted to share Emma Johnson's latest AI insights report with you. The analysis shows some interesting patterns in her learning:

Key Strengths:
${strengths.map((s, i) => `${i+1}. ${s.title}`).join('\n')}

Recommendations:
${recommendations.slice(0, 3).map((r, i) => `${i+1}. ${r.title}`).join('\n')}

Please let me know if you'd like to discuss these insights further or schedule a meeting.

Best regards,
[Parent Name]
    `);
    
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="bg-white border-b border-border sticky top-0 z-50">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <Link to="/dashboard">
              <Button variant="ghost" size="icon">
                <ArrowLeft className="h-5 w-5" />
              </Button>
            </Link>
            <div className="flex items-center gap-2">
              <Brain className="h-8 w-8 text-accent" />
              <span className="text-2xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                ChildTrack
              </span>
            </div>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-6 py-8">
        {/* Header */}
        <div className="mb-8 animate-fade-in">
          <h1 className="text-4xl font-bold mb-2">AI Insights</h1>
          <p className="text-muted-foreground text-lg">Personalized recommendations for Emma's growth</p>
        </div>

        {/* Cognitive Skills Analysis */}
        <Card className="mb-8 animate-fade-in">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Brain className="h-5 w-5 text-accent" />
              Cognitive Skills Analysis
            </CardTitle>
            <CardDescription>AI-powered assessment of learning strengths</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <h3 className="font-semibold mb-4">Skill Distribution</h3>
                <ResponsiveContainer width="100%" height={300}>
                  <RadarChart data={cognitiveData}>
                    <PolarGrid stroke="hsl(var(--border))" />
                    <PolarAngleAxis dataKey="skill" tick={{ fill: "hsl(var(--foreground))" }} />
                    <PolarRadiusAxis angle={90} domain={[0, 100]} />
                    <Radar
                      name="Emma"
                      dataKey="value"
                      stroke="hsl(var(--accent))"
                      fill="hsl(var(--accent))"
                      fillOpacity={0.5}
                    />
                  </RadarChart>
                </ResponsiveContainer>
              </div>
              <div>
                <h3 className="font-semibold mb-4">Strengths & Growth Areas</h3>
                <div className="space-y-4">
                  {strengths.map((strength, index) => (
                    <div key={index} className="p-4 rounded-lg bg-secondary/50">
                      <div className="flex items-start gap-3">
                        <div className="mt-1 h-6 w-6 rounded-full bg-accent flex items-center justify-center">
                          <span className="text-white text-xs font-bold">+</span>
                        </div>
                        <div>
                          <p className="font-medium">{strength.title}</p>
                          <p className="text-sm text-muted-foreground mt-1">{strength.description}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                  {growthAreas.map((area, index) => (
                    <div key={index} className="p-4 rounded-lg border border-border">
                      <div className="flex items-start gap-3">
                        <div className="mt-1 h-6 w-6 rounded-full bg-yellow-500 flex items-center justify-center">
                          <span className="text-white text-xs font-bold">↑</span>
                        </div>
                        <div>
                          <p className="font-medium">{area.title}</p>
                          <p className="text-sm text-muted-foreground mt-1">{area.description}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Learning Trends */}
        <div className="grid lg:grid-cols-2 gap-6 mb-8">
          <Card className="animate-fade-in">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="h-5 w-5 text-accent" />
                Learning Trends
              </CardTitle>
              <CardDescription>Progress over the last 6 months</CardDescription>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={learningTrends}>
                  <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                  <XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" />
                  <YAxis stroke="hsl(var(--muted-foreground))" />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: "hsl(var(--background))", 
                      borderColor: "hsl(var(--border))",
                      borderRadius: "var(--radius)",
                    }}
                  />
                  <Legend />
                  <Bar dataKey="engagement" name="Engagement" fill="hsl(var(--accent))" />
                  <Bar dataKey="performance" name="Performance" fill="hsl(var(--primary))" />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          <Card className="animate-fade-in">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BookOpen className="h-5 w-5 text-accent" />
                Subject Insights
              </CardTitle>
              <CardDescription>Performance across different subjects</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {subjectInsights.map((subject, index) => (
                  <div key={index} className="p-4 rounded-lg bg-secondary/50">
                    <div className="flex justify-between items-center mb-2">
                      <p className="font-medium">{subject.name}</p>
                      <span className="text-sm font-semibold">{subject.score}%</span>
                    </div>
                    <p className="text-sm text-muted-foreground">{subject.insight}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Detailed Recommendations */}
        <Card className="mb-8 animate-fade-in">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Lightbulb className="h-5 w-5 text-accent" />
              Detailed Recommendations
            </CardTitle>
            <CardDescription>Personalized strategies for continued growth</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
              {recommendations.map((rec, index) => (
                <div key={index} className="p-4 rounded-lg border border-border bg-secondary/50">
                  <div className="flex items-start gap-3">
                    <div className="mt-1 h-6 w-6 rounded-full bg-accent flex items-center justify-center">
                      <span className="text-white text-xs font-bold">{index + 1}</span>
                    </div>
                    <div>
                      <p className="font-medium">{rec.title}</p>
                      <p className="text-sm text-muted-foreground mt-1">{rec.description}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-4 justify-center">
          <Button variant="hero" className="gap-2" onClick={handleDownloadReport}>
            <Download className="h-5 w-5" />
            Download Full Insights Report
          </Button>
          <Button variant="outline" className="gap-2" onClick={handleShareWithTeacher}>
            <Users className="h-5 w-5" />
            Share with Teacher
          </Button>
        </div>
      </div>
    </div>
  );
};

const cognitiveData = [
  { skill: "Logic", value: 92 },
  { skill: "Memory", value: 85 },
  { skill: "Creativity", value: 88 },
  { skill: "Analysis", value: 95 },
  { skill: "Verbal", value: 82 },
  { skill: "Spatial", value: 90 },
];

const strengths = [
  {
    title: "Analytical Thinking",
    description: "Emma demonstrates exceptional ability to break down complex problems into manageable components."
  },
  {
    title: "Pattern Recognition",
    description: "Strong ability to identify patterns and relationships in data, especially in mathematics."
  },
  {
    title: "Logical Reasoning",
    description: "Consistently applies logical principles to solve problems and make decisions."
  }
];

const growthAreas = [
  {
    title: "Verbal Expression",
    description: "Opportunity to enhance written and verbal communication skills through practice."
  },
  {
    title: "Creative Thinking",
    description: "Encourage exploration of creative outlets to further develop imaginative thinking."
  }
];

const learningTrends = [
  { month: "Jun", engagement: 75, performance: 82 },
  { month: "Jul", engagement: 78, performance: 84 },
  { month: "Aug", engagement: 82, performance: 87 },
  { month: "Sep", engagement: 85, performance: 89 },
  { month: "Oct", engagement: 88, performance: 91 },
  { month: "Nov", engagement: 90, performance: 92 },
];

const subjectInsights = [
  {
    name: "Mathematics",
    score: 92,
    insight: "Exceptional problem-solving skills. Ready for advanced topics."
  },
  {
    name: "Science",
    score: 88,
    insight: "Strong analytical abilities. Encourage more hands-on experiments."
  },
  {
    name: "English",
    score: 85,
    insight: "Good comprehension. Focus on creative writing development."
  },
  {
    name: "History",
    score: 90,
    insight: "Excellent recall and analysis of historical events."
  }
];

const recommendations = [
  {
    title: "Advanced Math Challenges",
    description: "Introduce Emma to competition-level mathematics problems to further develop her analytical skills."
  },
  {
    title: "Creative Writing Program",
    description: "Enroll in a creative writing workshop to enhance verbal expression and storytelling abilities."
  },
  {
    title: "Collaborative Projects",
    description: "Continue encouraging group work to build leadership and teamwork skills."
  },
  {
    title: "Reading Diversity",
    description: "Introduce literature from different cultures and time periods to broaden perspective."
  },
  {
    title: "Memory Techniques",
    description: "Teach advanced memory techniques to support learning in all subjects."
  },
  {
    title: "STEM Club",
    description: "Join the school's STEM club to apply analytical skills in real-world projects."
  }
];

export default Insights;